# Generated by Django 4.0.6 on 2022-07-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_blogpost_tumbnail_alter_blogpost_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tumbnail',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
    ]
